"""Discoverable collection bounds shared by Kanban validation and planning."""

from __future__ import annotations


DASHBOARD_LAYOUT_MAX_ITEMS = 20
DASHBOARD_DELETE_BATCH_MAX_ITEMS = 100
NOTE_BATCH_MAX_ITEMS = 20
ORDER_ROOT_BATCH_MAX_ITEMS = 1_000
PREPARE_MAX_ITEMS = 100_000
PREPARE_MAX_PAGES = 1_000
PREPARE_MAX_WORKERS = 24
REPORT_LINK_BATCH_MIN_ITEMS = 1
REPORT_LINK_BATCH_MAX_ITEMS = 20
REPORT_UNLINK_BATCH_MIN_ITEMS = 1
REPORT_UNLINK_BATCH_MAX_ITEMS = 100


__all__ = [
    "DASHBOARD_DELETE_BATCH_MAX_ITEMS",
    "DASHBOARD_LAYOUT_MAX_ITEMS",
    "NOTE_BATCH_MAX_ITEMS",
    "ORDER_ROOT_BATCH_MAX_ITEMS",
    "PREPARE_MAX_ITEMS",
    "PREPARE_MAX_PAGES",
    "PREPARE_MAX_WORKERS",
    "REPORT_LINK_BATCH_MAX_ITEMS",
    "REPORT_LINK_BATCH_MIN_ITEMS",
    "REPORT_UNLINK_BATCH_MAX_ITEMS",
    "REPORT_UNLINK_BATCH_MIN_ITEMS",
]
