from __future__ import annotations

import hashlib
import json
from collections import Counter, defaultdict
from collections.abc import Callable, Iterable, Mapping, Sequence
from pathlib import Path
from typing import Any

from gravity_sdk import json_output


def json_bytes(value: Any) -> bytes:
    return (
        json_output.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    ).encode("utf-8")


def write_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(json_bytes(value))


def read_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def stable_bundle_id(files: list[dict[str, Any]]) -> str:
    rows = [f"{item['url']}\t{item['sha256']}\t{item['size']}" for item in files]
    return sha256_bytes(("\n".join(sorted(rows)) + "\n").encode("utf-8"))


def _coverage_overview_lines(document: dict[str, Any]) -> list[str]:
    summary = document["summary"]
    reconciliation = document["manifest_reconciliation"]
    breakdown = reconciliation["previously_missing_breakdown"]
    lines = [
        "# Gravity frontend route coverage", "",
        "> Generated by `python -m gravity_sdk.census coverage`. Do not edit by hand.", "",
        "## Scope and certainty", "",
        f"- Bundle complete: `{str(document.get('source', {}).get('bundle_complete', False)).lower()}`",
        f"- Routes classified: **{summary['total_routes']}**",
        f"- Public-entry static graph boundary: {document['scope_boundary']['proven']}.",
        f"- Not proven: {document['scope_boundary']['not_proven']}.",
        "- `covered` requires a stable manifest method+path match. Read/write/export/auth labels carry per-route evidence.",
        "- Unconfirmed POST read signals are `unsafe_unknown`; exact reviewed confirmations may be `uncovered_read`.",
        "", "## Coverage summary", "", "| status | routes |", "| --- | ---: |",
    ]
    statuses = (
        "covered", "uncovered_read", "uncovered_write", "uncovered_export",
        "uncovered_auth_or_proxy", "static_read_candidate", "unsafe_unknown",
        "unsupported_non_api", "unclassified",
    )
    lines.extend(f"| `{key}` | {summary[key]} |" for key in statuses)
    lines.extend([
        "", "## Route accounting vs callability", "",
        f"- Accounted routes: **{summary['accounted']}**",
        f"- Callable covered routes: **{summary['callable_covered']}**",
        f"- Unaccounted routes: **{summary['unaccounted']}**", "",
        "| accounting state | routes |", "| --- | ---: |",
    ])
    lines.extend(f"| `{key}` | {value} |" for key, value in document["accounting_summary"].items())
    lines.extend(["", "| callability | routes |", "| --- | ---: |"])
    lines.extend(f"| `{key}` | {value} |" for key, value in document["callability_summary"].items())
    lines.extend([
        "", "## Stable manifest reconciliation", "", "| category | stable operations |",
        "| --- | ---: |",
        f"| Previously covered | {reconciliation['summary'].get('previously_covered', 0)} |",
        f"| (a) Found in previously unfetched chunks | {breakdown['a_previously_unfetched_chunk']} |",
        f"| (b) Normalization false gap fixed | {breakdown['b_normalization_false_gap_fixed']} |",
        f"| (c) Manifest route absent from frontend | {breakdown['c_manifest_route_absent_from_frontend']} |",
        "", "### Manifest routes absent from frontend", "",
        "| operation | method | manifest path | similar frontend routes |",
        "| --- | --- | --- | --- |",
    ])
    for item in reconciliation["operations"]:
        if item["category"] != "manifest_route_absent_from_frontend":
            continue
        similar = "; ".join(
            f"{candidate['method']} {candidate['path']}" for candidate in item["similar_frontend_routes"]
        ) or "None"
        lines.append(
            f"| `{item['operation_id']}` | `{item['method']}` | `{item['path']}` | `{similar}` |"
        )
    return lines


def _coverage_module_lines(
    document: dict[str, Any], promotion_levels: Sequence[str]
) -> list[str]:
    lines = [
        "", "## Business module read gaps", "",
        "| module | covered | uncovered read | all uncovered | total |",
        "| --- | ---: | ---: | ---: | ---: |",
    ]
    lines.extend(
        f"| {item['module']} | {item['covered']} | {item['uncovered_read']} | {item['uncovered']} | {item['total']} |"
        for item in document["module_summary"]
    )
    lines.extend([
        "", "## Promotion platform x level uncovered reads", "",
        "| platform | 账户 | 项目 | 计划 | 广告组 | 广告/创意 | 素材 | 报表 | 其它 | total |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
    ])
    for item in document["promotion_gap_matrix"]:
        values = [item["levels"][level]["uncovered_read"] for level in promotion_levels]
        lines.append(
            f"| {item['platform']} | " + " | ".join(str(value) for value in values) + f" | {sum(values)} |"
        )
    return lines


def _coverage_family_cost_lines(document: dict[str, Any]) -> list[str]:
    family_summary = document["family_summary"]
    lines = [
        "", "## Contract families", "", f"- Families: **{family_summary['families']}**",
        f"- Uncovered reads assigned to a family: **{family_summary['uncovered_read_routes_with_family']} / {family_summary['uncovered_read_routes']} ({family_summary['coverage_ratio']:.1%})**",
        "", "| family | kind | members | signature |", "| --- | --- | ---: | --- |",
    ]
    for family in document["contract_families"]:
        signature = family["signature"].replace("|", "\\|")
        lines.append(
            f"| `{family['family_id']}` | `{family['family_kind']}` | {family['member_count']} | `{signature}` |"
        )
    costs = document["read_cost_summary"]
    lines.extend([
        "", "## Estimated implementation cost", "", "| tier | uncovered reads | rule |",
        "| --- | ---: | --- |",
        f"| 低 | {costs['低']} | Flat list/detail with no evident parent dependency |",
        f"| 中 | {costs['中']} | Parent-resource dependency or structured selector |",
        f"| 高 | {costs['高']} | Complex query/report body, proxy envelope, or dynamic path |",
        "", "Cost is a scheduling heuristic, not an observed implementation duration.",
    ])
    return lines


def _coverage_uncovered_read_lines(
    document: dict[str, Any], modules: Sequence[str]
) -> list[str]:
    by_module: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for item in document["routes"]:
        if item["status"] == "uncovered_read":
            by_module[item["business_module"]].append(item)
    lines = ["", "## Complete uncovered read route list", ""]
    for module in modules:
        items = by_module[module]
        lines.extend([f"### {module} ({len(items)})", ""])
        if not items:
            lines.extend(["None.", ""])
            continue
        lines.extend([
            "| confidence | method | path | family | cost |",
            "| --- | --- | --- | --- | --- |",
        ])
        for item in items:
            escaped = item["path"].replace("|", "\\|")
            family = item["contract_family"]["family_id"] if item["contract_family"] else "singleton"
            lines.append(
                f"| `{item['semantic_confidence']}` | `{item['method']}` | `{escaped}` | `{family}` | `{item['estimated_implementation_cost']}` |"
            )
        lines.append("")
    return lines


def render_coverage_report(
    document: dict[str, Any], modules: Sequence[str], promotion_levels: Sequence[str]
) -> str:
    lines = _coverage_overview_lines(document)
    lines.extend(_coverage_module_lines(document, promotion_levels))
    lines.extend(_coverage_family_cost_lines(document))
    lines.extend(_coverage_uncovered_read_lines(document, modules))
    return "\n".join(lines).rstrip() + "\n"


def all_parameter_nodes(
    parameters: Iterable[Mapping[str, Any]],
) -> Iterable[Mapping[str, Any]]:
    for parameter in parameters:
        yield parameter
        yield from all_parameter_nodes(parameter.get("properties", []))
        items = parameter.get("items")
        if isinstance(items, Mapping):
            yield from all_parameter_nodes(items.get("properties", []))


def _parameter_names(route: Mapping[str, Any]) -> set[str]:
    result: set[str] = set()
    for location in ("path_parameters", "query_parameters", "body_parameters"):
        for item in all_parameter_nodes(route.get(location, [])):
            name = item.get("name")
            if isinstance(name, str):
                result.add(name)
    return result


def _parameter_coverage(
    keys: set[tuple[str, str]], routes: Mapping[tuple[str, str], Mapping[str, Any]]
) -> dict[str, int]:
    selected = [routes[key] for key in sorted(keys) if key in routes]
    return {
        "total": len(keys),
        "route_matched": len(selected),
        "with_parameter_contract": sum(item["status"] == "extracted" for item in selected),
        "with_any_high_confidence_parameter": sum(
            any(
                node.get("confidence") == "high"
                for location in ("path_parameters", "query_parameters", "body_parameters")
                for node in all_parameter_nodes(item.get(location, []))
            )
            for item in selected
        ),
        "with_high_confidence_complete_contract": sum(
            item["status"] == "extracted" and item["contract_confidence"] == "high"
            for item in selected
        ),
    }


def _evidence_hint_names(evidence_path: Path) -> set[str]:
    if not evidence_path.is_file():
        return set()
    evidence = read_json(evidence_path)
    names: set[str] = set()
    for observation in evidence.get("http", []):
        for item in observation.get("response_schema_sketch", {}).get("paths", []):
            raw = item.get("path") if isinstance(item, Mapping) else None
            if not isinstance(raw, str) or not raw.startswith("$.extra."):
                continue
            name = raw[len("$.extra.") :].split(".", 1)[0].removesuffix("[]")
            if name not in {"error", "show_message", "request_id"}:
                names.add(name)
    return names


def _semantic_hint_validation(
    batch_items: Sequence[Mapping[str, Any]],
    by_key: Mapping[tuple[str, str], Mapping[str, Any]],
    repo_root: Path,
    route_key: Callable[[Any, Any], tuple[str, str]],
) -> dict[str, Any]:
    validation_rows: list[dict[str, Any]] = []
    semantic_errors = [item for item in batch_items if item.get("latest_conclusion") == "semantic_error"]
    for item in semantic_errors:
        raw_path = item.get("latest_evidence")
        if not isinstance(raw_path, str) or not (hints := _evidence_hint_names(repo_root / raw_path)):
            continue
        route = by_key.get(route_key(item.get("method"), item.get("path")))
        overlap = hints & (_parameter_names(route) if route else set())
        validation_rows.append(
            {
                "hint_fields": sorted(hints), "matched_fields": sorted(overlap),
                "method": item.get("method"), "operation_id": item.get("operation_id"),
                "path": item.get("path"), "verdict": "matched" if overlap else "mismatched",
            }
        )
    verdicts = Counter(row["verdict"] for row in validation_rows)
    primary_rows = [
        row for row in validation_rows
        if next((item.get("failure_reason") for item in batch_items
                 if item.get("operation_id") == row["operation_id"]), None) == "参数不明"
    ]
    assessable = len(validation_rows)
    return {
        "assessable": assessable,
        "evidence_without_parameter_hint": len(semantic_errors) - assessable,
        "matched": verdicts["matched"], "mismatched": verdicts["mismatched"],
        "match_rate": round(verdicts["matched"] / assessable, 6) if assessable else None,
        "parameter_unknown_primary_assessable": len(primary_rows),
        "parameter_unknown_primary_matched": sum(row["verdict"] == "matched" for row in primary_rows),
        "semantic_error_responses": len(semantic_errors), "rows": validation_rows,
    }


def _draft_parameter_blockers(
    drafts_root: Path | None, route_key: Callable[[Any, Any], tuple[str, str]]
) -> set[tuple[str, str]]:
    blocker_keys: set[tuple[str, str]] = set()
    if not drafts_root or not drafts_root.is_dir():
        return blocker_keys
    for path in sorted(drafts_root.glob("*.json")):
        source = read_json(path)
        blockers = source.get("draft", {}).get("blockers", [])
        if any(item.get("code") == "request_parameters_required" for item in blockers):
            operation = source.get("operation", {})
            blocker_keys.add(route_key(operation.get("upstream_method"), operation.get("path_template")))
    return blocker_keys


def batch_parameter_validation(
    route_documents: Sequence[Mapping[str, Any]],
    route_path: Callable[[str], str],
    *,
    repo_root: Path,
    batch_results_path: Path | None,
    drafts_root: Path | None,
) -> dict[str, Any]:
    def route_key(method: Any, path: Any) -> tuple[str, str]:
        return str(method).upper(), route_path(str(path))

    by_key = {route_key(item["method"], item["path"]): item for item in route_documents}
    result: dict[str, Any] = {
        "code_1004_replayability": "unavailable_response_values_were_not_persisted",
        "parameter_unknown_primary": _parameter_coverage(set(), by_key),
        "request_parameter_blockers": _parameter_coverage(set(), by_key),
        "semantic_error_parameter_hints": {
            "assessable": 0, "matched": 0, "mismatched": 0, "match_rate": None,
        },
        "successful_probes": {"total": 0, "route_matched": 0},
    }
    if batch_results_path and batch_results_path.is_file():
        payload = read_json(batch_results_path)
        batch_items = list(payload.get("results", [])) if isinstance(payload, Mapping) else []
        primary_keys = {
            route_key(item.get("method"), item.get("path"))
            for item in batch_items if item.get("failure_reason") == "参数不明"
        }
        successful = [item for item in batch_items if item.get("successful") is True]
        result["parameter_unknown_primary"] = _parameter_coverage(primary_keys, by_key)
        result["successful_probes"] = {
            "total": len(successful),
            "route_matched": sum(route_key(item.get("method"), item.get("path")) in by_key
                                 for item in successful),
        }
        result["semantic_error_parameter_hints"] = _semantic_hint_validation(
            batch_items, by_key, repo_root, route_key
        )
    result["request_parameter_blockers"] = _parameter_coverage(
        _draft_parameter_blockers(drafts_root, route_key), by_key
    )
    return result


def _parameter_nodes_by_location(
    routes: Sequence[Mapping[str, Any]], locations: Sequence[str]
) -> dict[str, list[Mapping[str, Any]]]:
    return {
        location: [node for route in routes
                   for node in all_parameter_nodes(route.get(f"{location}_parameters", []))]
        for location in locations
    }


def _observed_default_count(nodes: Sequence[Mapping[str, Any]]) -> int:
    return sum("default" in node or "observed_defaults" in node for node in nodes)


def _complete_contract_count(routes: Sequence[Mapping[str, Any]]) -> int:
    return sum(
        route["status"] == "extracted" and route["contract_confidence"] == "high"
        for route in routes
    )


def summarize_parameter_routes(routes: Sequence[Mapping[str, Any]]) -> dict[str, Any]:
    locations = ("path", "query", "body")
    nodes_by_location = _parameter_nodes_by_location(routes, locations)
    nodes = [node for location in locations for node in nodes_by_location[location]]
    confidence_counts = Counter(node.get("confidence") for node in nodes)
    required_counts = Counter(node.get("required") for node in nodes)
    statuses = Counter(route["status"] for route in routes)
    top_level = {location: sum(len(route.get(f"{location}_parameters", [])) for route in routes)
                 for location in locations}
    return {
        "confidence": {level: confidence_counts[level] for level in ("high", "medium", "low")},
        "defaults_observed": _observed_default_count(nodes),
        "parameter_nodes": len(nodes),
        "parameter_nodes_by_location": {location: len(nodes_by_location[location])
                                        for location in locations},
        "required": {state: required_counts[state]
                     for state in ("observed_always", "observed_conditional", "unknown")},
        "routes_observed_empty": statuses["observed_empty"], "routes_total": len(routes),
        "routes_unknown": statuses["unknown"], "routes_with_parameters": statuses["extracted"],
        "routes_with_high_confidence_complete_contract": _complete_contract_count(routes),
        "top_level_parameters": {**top_level, "total": sum(top_level.values())},
    }
