"""Generate the small, contract-derived Agent task guide set."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "agent-skills"


class _OfflineClient:
    def validate(self, *_args: Any, **_kwargs: Any) -> dict[str, Any]:
        return {"ok": True, "status": "needs_live_metadata", "live_metadata_dependencies": []}

    def operations(self, **_kwargs: Any) -> list[dict[str, Any]]:
        return []

    def search_operations(self, *_args: Any, **_kwargs: Any) -> dict[str, Any]:
        return {"operations": []}


def render_documents() -> dict[Path, str]:
    from gravity_sdk.agent import _protocol, discover_capabilities
    from gravity_sdk.agent_analysis import analysis_query_spec_cards
    from gravity_sdk.agent_batch_sources import AgentSourceSnapshot
    from gravity_sdk.analysis_period_compare import compare_analysis_periods
    from gravity_sdk.analysis_spec import prepare_query_spec
    from gravity_sdk.analysis_spec_schema import analysis_query_spec_schema

    protocol = _protocol()
    event_card = analysis_query_spec_cards("analysis.query.spec:event", domain=None, platform=None)[0]
    compare_card = analysis_query_spec_cards("analysis period compare", domain=None, platform=None)[0]
    event_preview = prepare_query_spec(
        _OfflineClient(), "event", _event_spec(), app="1"
    )
    comparison_gap = compare_analysis_periods(
        object(), "property", {}, baseline_start="2026-01-01", baseline_end="2026-01-02"
    )
    discovery_gap = discover_capabilities(
        "unregistered capability",
        client=_OfflineClient(),
        sources=AgentSourceSnapshot(
            workspace=None, operation_inventory=(), recipe_inventory=(),
            product_inventory=(), metadata_inventory=(), composite_inventory=(),
            warnings=(), workspace_fingerprint="generated", metadata_catalog_available=True,
        ),
    )
    contract = analysis_query_spec_schema()
    exits = protocol["exit_codes"]
    return {
        OUTPUT / "index.md": _index(),
        OUTPUT / "event-trend.md": _event_trend(event_card, contract, event_preview, exits),
        OUTPUT / "period-comparison.md": _comparison(compare_card, contract, comparison_gap, exits),
        OUTPUT / "capability-gap.md": _capability_gap(protocol, discovery_gap, exits),
        OUTPUT / "ten-minute-path.md": _ten_minute_path(event_card, contract, exits),
    }


def _index() -> str:
    return """<!-- generated by scripts/generate_agent_skills.py; do not edit -->
# Agent 任务指南

这些短指南从现有 Agent card、Analysis Spec contract、错误合同和 manifest 生成；不创建 Skill 注册表，也不替代运行时合同。

| 目标 | 指南 |
| --- | --- |
| 十分钟内确认本地能力并准备第一次分析 | [十分钟路径](ten-minute-path.md) |
| 看一个事件的趋势 | [事件趋势](event-trend.md) |
| 用同一分析定义比较两个时期 | [时期对比](period-comparison.md) |
| Agent 返回 `capability_gap` | [能力缺口](capability-gap.md) |
"""


def _event_trend(card: dict[str, Any], contract: dict[str, Any], preview: dict[str, Any], exits: dict[str, str]) -> str:
    return _guide(
        "看某个事件的趋势",
        [
            "```powershell\n" + _argv(card["next"]["schema_argv"]) + "\n```",
            "将返回的 `" + card["spec_schema_version"] + "` schema 中事件名、指标和日期填入 Spec 后执行：",
            "```powershell\n" + contract["handoff"]["command"] + "\n```",
        ],
        preview,
        exits,
        "`validation.live_metadata_dependencies` 非空时，先按该字段列出的登记 operation 校验物理事件/字段；不要由自然语言补值。",
    )


def _comparison(card: dict[str, Any], contract: dict[str, Any], gap: dict[str, Any], exits: dict[str, str]) -> str:
    flags = " ".join(f"--{name.replace('_', '-')} <explicit-date>" for name in card["optional_inputs"])
    return _guide(
        "比较两个时期",
        [
            "先取得同一 kind 的 Spec，再只追加 card 声明的时期参数：",
            "```powershell\n" + contract["handoff"]["command"] + " " + flags + "\n```",
            "此卡的 compare contract 是 `" + card["period_compare"]["schema_version"] + "`；仅支持 `" + "/".join(card["period_compare"]["supported_kinds"]) + "`。",
        ],
        gap,
        exits,
        "若 `status=capability_gap`，读取 `next_action`；不要把没有 delta 当作 0。",
    )


def _capability_gap(protocol: dict[str, Any], gap: dict[str, Any], exits: dict[str, str]) -> str:
    command = list(protocol["workflow"][0]["argv"])
    command[-1] = '"<your-query>"'
    return _guide(
        "拿到 capability_gap 后怎么办",
        [
            "```powershell\n" + _argv(command) + "\n```",
            "只有 `status=success` 的 candidate 才可执行；`capability_gaps` 是明确的不可执行结果，不是 empty。",
        ],
        gap,
        exits,
        "先报告 `capability_gaps[].code`、`reason` 和 `next_action`。仅在其 `next.argv` 存在时执行该受控下一步；不要执行 weak match。",
    )


def _ten_minute_path(card: dict[str, Any], contract: dict[str, Any], exits: dict[str, str]) -> str:
    return _guide(
        "十分钟路径：从仓库到第一次分析准备",
        [
            "```powershell\npython -m pip install -e .\ngravity agent-catalog categories\ngravity agent-catalog category analysis --limit 20\n" + _argv(card["next"]["schema_argv"]) + "\n```",
            "选择 `" + card["selector"] + "` 后，按 schema 写 Spec；然后执行：",
            "```powershell\n" + contract["handoff"]["command"] + "\n```",
        ],
        {"schema_version": card["spec_schema_version"], "required_inputs": card["required_inputs"], "next": card["next"]},
        exits,
        "前四条命令完全离线，只证明本地合同可用。真实业务结果还需要可用的登录、已知 App 和已登记事件/指标；这些输入不是 SDK 可以猜出的业务语义。",
    )


def _guide(title: str, steps: list[str], envelope: dict[str, Any], exits: dict[str, str], next_step: str) -> str:
    return "\n".join((
        "<!-- generated by scripts/generate_agent_skills.py; do not edit -->",
        f"# {title}", "", *steps, "", "## 预期 envelope 形状", "",
        "```json", json.dumps(_shape(envelope), ensure_ascii=False, indent=2, sort_keys=True), "```", "",
        "## 失败分支", "",
        *[f"- exit {code}: {meaning}." for code, meaning in sorted(exits.items(), key=lambda item: int(item[0]))],
        "", "## 下一步", "", next_step, "",
    ))


def _shape(value: Any) -> Any:
    if isinstance(value, dict):
        return {key: _shape(item) for key, item in value.items()}
    if isinstance(value, list):
        return [_shape(value[0])] if value else []
    return f"<{type(value).__name__}>"


def _event_spec() -> dict[str, Any]:
    return {
        "start": "2026-01-01", "end": "2026-01-02",
        "steps": [{"event": "example_event", "metric": {"field": "event_count", "aggregation": "Count"}}],
    }


def _argv(values: list[str]) -> str:
    return " ".join(values)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render_documents()
    mismatched = [path for path, content in rendered.items() if not path.is_file() or path.read_text(encoding="utf-8") != content]
    if args.check:
        if mismatched:
            raise SystemExit("generated Agent guides are stale: " + ", ".join(str(path.relative_to(ROOT)) for path in mismatched))
        return 0
    for path, content in rendered.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
